language: cpp

notifications:
  email: false

script:
- cmake -H. -B_build
- cmake --build _build
- cd _build
- cpack -G "TGZ"
- cpack -G "DEB"
- cd ..

- cmake -H. -B_build -DCPACK_GENERATOR="TGZ"
- cmake --build _build --target package

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
